FROM ubuntu:latest
MAINTAINER Ruud van Engelenhoven

RUN apt-get update && apt-get install -y \
    apt-utils \
    cron \
    curl \
    git \
    openssl \
    ssh \
    sudo \
    supervisor \
    unzip \
    vim \
    wget